# Adapted from: https://github.com/hku-mars/FAST-LIVO2/issues/43

common:
  lid_topic: "/hesai/pandar"
  imu_topic: "/imu/data"
  ros_driver_bug_fix: false
  image_en: 1
  lidar_en: 1
  img_topic: "/econ/cam1/color/image"

time_offset:
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

vio:
  raycast_en: false
  patch_size: 16

imu:
  imu_en: true
  imu_int_frame: 1
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001

preprocess:
  lidar_type: 5       # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
  scan_line: 64
  timestamp_unit: 3      # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
  blind: 1
  point_filter_num: 1

extrin_calib:
  extrinsic_T: [0.01256473, 0.00184937, -0.07039029]
  extrinsic_R: [ 0.99949463,  0.03141028, -0.00488706,
                 0.03142951, -0.99949832,  0.0039102,
                -0.00476179, -0.00406182, -0.99998041]
  Rcl: [-0.00342026,  0.99992363,  0.01187548, 
        -0.00505442,  0.01185811, -0.99991692, 
        -0.99998138, -0.00348,     0.00501347]
  Pcl: [0.001704541183222788, -0.07129301622086368, -0.054046027107931834]

evo:
  seq_name: "whytham-site4-tree"
  pose_output_en: true
